name: eduquiz
description: "A new Flutter project."
publish_to: none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/EduQuiz.png
    - lib/Francais.jpg
    - lib/Geographie.png
    - lib/Histoire.png
    - lib/Maths.jpg
    - lib/Sciences.jpg
    - lib/Economie.png
    - lib/Education.jpg